src/SmartAdmin.WebUI/Controllers/AspNetCoreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SmartAdmin.WebUI.Controllers
{
    [AllowAnonymous]
    public class AspNetCoreController : Controller
    {
        public IActionResult Welcome() => View();
        public IActionResult Interactive() => View();
        public IActionResult Editions() => View();
        public IActionResult Faq() => View();
    }
}

src/SmartAdmin.WebUI/Views/AspNetCore/Faq.cshtml
@{
    ViewData["Title"] = "FAQ";
    ViewData["PageName"] = "aspnetcore_faq";
    ViewData["Heading"] = "<i class='fal fa-folder-open'></i> FAQ: <span class='fw-300'>Common issues</span>";
    ViewData["Category1"] = "Solution Overview";
}

<div class="row">
    <div class="col-xl-12">
        <div class="panel">
            <div class="panel-hdr">
                <h2>
                    Frequently Asked Questions for @Settings.AppFlavor
                </h2>
            </div>
            <div class="panel-container show">
                <div class="panel-container show">
                    <div class="panel-content">
                        <div class="accordion accordion-hover" id="js_demo_accordion-5">
                            <div class="card">
                                <div class="card-header">
                                    <a href="javascript:void(0);" class="card-title pb-2 pt-2 bg-white text-primary fs-lg border-bottom border-dashed border-faded">
                                        <i class="fal fa-cog width-2 fs-xl"></i>
                                        Installation: I am getting a message stating that <code class="bg-transparent mx-1">dotnet</code> is not a valid command?
                                    </a>
                                </div>
                                <div class="collapse show">
                                    <div class="card-body">
                                        This happens when <code>cmd.exe</code> is running as a 32-bit process. You can install the 32-bit version of the ASP.NET Core 3.1 SDK in order to use the <code>dotnet</code> command in your command line tool of choice.
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-header">
                                    <a href="javascript:void(0);" class="card-title pb-2 pt-2 bg-white text-primary fs-lg border-bottom border-dashed border-faded">
                                        <i class="fal fa-shield width-2 fs-xl"></i>
                                        I am getting a browser warning about an insecure website?
                                    </a>
                                </div>
                                <div class="collapse show">
                                    <div class="card-body">
                                        This is most likely because there is no localhost certificate available on your computer or the one installed has not been marked trusted yet.
                                        You can run <code>dotnet dev-certs https --trust</code> in an elevated command prompt to enable trust on the development certificate.
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-header">
                                    <a href="javascript:void(0);" class="card-title pb-2 pt-2 bg-white text-primary fs-lg border-bottom border-dashed border-faded">
                                        <i class="fal fa-database width-2 fs-xl"></i>
                                        I am getting an error that the application cannot start because of missing database migrations?
                                    </a>
                                </div>
                                <div class="collapse show">
                                    <div class="card-body">
                                        You can follow the instructions shown on the page and click the big <strong>blue</strong> button that says: <code>Apply migration</code>.
                                        This will initialize your database platform with the necessary tables to allow you to create and authenticate users.
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-header">
                                    <a href="javascript:void(0);" class="card-title pb-2 pt-2 bg-white text-primary fs-lg border-bottom border-dashed border-faded">
                                        <i class="fal fa-lock width-2 fs-xl"></i>
                                        I am getting an error similar to: 'Invalid login attempt'?
                                    </a>
                                </div>
                                <div class="collapse show">
                                    <div class="card-body">
                                        This means that the preconfigured user does not exist (yet) in your local database.
                                        You can go ahead to the Register page to create the user and afterwards you should be able to login with the <strong>pre-filled credentials</strong> to enter the main website.
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-header">
                                    <a href="javascript:void(0);" class="card-title pb-2 pt-2 bg-white text-primary fs-lg border-bottom border-dashed border-faded">
                                        <i class="fal fa-lock width-2 fs-xl"></i>
                                        Why is the <code class="bg-transparent mx-1">nav.json</code> file served from the root of the project?
                                    </a>
                                </div>
                                <div class="collapse show">
                                    <div class="card-body">
                                        Typically most websites will have <strong>StaticFiles</strong> enabled and this would allow the files to be downloaded.
                                        All files that should be accesible by your visitors is served from the <strong>wwwroot</strong> directory; the navigation sources do not qualify for this as the file is assumed to be of temporary nature.
                                        Furthermore it exists mainly for demo purposes as the assumption is made that you would most likely add the ability to generate a dynamic menu from other data sources, such as a database.
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-header">
                                    <a href="javascript:void(0);" class="card-title pb-2 pt-2 bg-white text-primary fs-lg border-bottom border-dashed border-faded">
                                        <i class="fal fa-lock width-2 fs-xl"></i>
                                        Why is feature <code class="bg-transparent mx-1">Xyz</code> or functionality <code class="bg-transparent mx-1">Acme</code> not included in the project by default?
                                    </a>
                                </div>
                                <div class="collapse show">
                                    <div class="card-body">
                                        <p>
                                            First and foremost, this project is not meant to serve as a <strong>1-in-all</strong> solution for your project start to finish.
                                            It was built and structured in such a way that it can be used as a starting point based on the set of features that speak the most to your intent and purpose (Please see the <a asp-controller="AspNetCore" asp-action="Editions">Editions</a> page to help you decide).
                                        </p>
                                        <p>
                                            While we certainly understand your frustration when a specific feature you were looking forward to is not included, we also assume you yourself are perfectly capable of expanding the features of your project over time.
                                            <br/>
                                            If and when a new update happens to include the feature you were (patiently) waiting for, great!
                                            <br/>
                                            Still not added to the project? What?! Don't worry :-) Feel free to let us know on the <a href="https://support.gotbootstrap.com/t/asp-net-core" target="_blank">Supports Forum</a> so we track the interest and see about getting it added in the next version of the template.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/SmartAdmin.WebUI/Views/AspNetCore/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome";
    ViewData["PageName"] = "aspnetcore_welcome";
    ViewData["Heading"] = "<i class='fal fa-graduation-cap'></i> Welcome: <span class='fw-300'>SmartAdmin for .NET Core</span>";
}

<div class="row">
    <div class="col-xl-12">
        <div class="panel">
            <div class="panel-hdr">
                <h2>
                    Introducing @Settings.App for @Settings.AppFlavor
                </h2>
            </div>
            <div class="panel-container show">
                <div class="panel-content">
                    <p>
                        After the great success of our previous version of @Settings.App we knew we had to do our utmost best to deliver you the latest and greatest when it comes to Bootstrap based theming.
                        Our journey has not been without challenges and at one point we concluded that the best approach was to completely reboot our framework, not only on how we wanted to setup the template, but also provide a much better customer journey with a strong focus on getting you started quickly, hassle-free!
                        Whether you are a seasoned @Settings.App veteran or a new customer of @Settings.App, we got you covered! And to start off with that we retained the unique look and feel of @Settings.App but brought it up to the newest industry standards, supporting the latest capabilities of your favorite frameworks and plugins.
                    </p>
                    <h3>
                        Doing more with less
                    </h3>
                    <p>
                        This has been our core motto during the rebuilt of @Settings.App 4.0 and has helped us to stay focused and keep our promise to deliver you a cutting-edge redesign of your favorite Bootstrap template!
                    </p>
                    <p>
                        Part of the rebuilt was to ensure we would be able to provide better out of the box integrations with the most popular tech-stacks for building web applications.
                        You can head over to the <a href="https://smartadmin-core.azurewebsites.net/info/appflavors">App Flavors</a> page to see our current selection of frameworks that will be made available upon release.
                        You can expect these to grow over time as we include more frameworks that have been requested by our community.
                    </p>
                    <p>
                        @Settings.App 4.0 is built with full support for <strong>npm</strong> packages and uses <strong>gulp</strong> to build the site structure.
                        All of this with a strong emphasis on automation and testing to ensure that you not only get a fully fledged solution but a solid framework that meets our own high standards for both building and writing applications.
                    </p>
                    <h3>Template Versions</h3>
                    <p>
                        In the tradition of @Settings.App for @Settings.AppFlavor we plan to include the following editions with this version:
                    </p>
                    <ul>
                        <li>
                            <strong>@Settings.App for @Settings.AppFlavor - Bare</strong>
                            <blockquote>
                                Want to start from scratch and slowly add your site structure and pages?
                                Then <strong>Bare</strong> will be your best starting point.
                            </blockquote>
                        </li>
                        <li>
                            <strong>@Settings.App for @Settings.AppFlavor - Slim</strong>
                            <blockquote>
                                Need a light version with minimal plugins and fast page loading without compromise?
                                No database or authentication support required?
                                Then <strong>Slim</strong> will be your best starting point.
                            </blockquote>
                        </li>
                        <li>
                            <strong>@Settings.App for @Settings.AppFlavor - Seed</strong>
                            <blockquote>
                                Want to checkout all the pages SmartAdmin has to offer, such as Dashboards, Charts, Chat and other cool features?
                                Then <strong>Seed</strong> will allow you to view all the required markup to start planning the features you want to include.
                            </blockquote>
                        </li>
                        <li>
                            <strong>@Settings.App for @Settings.AppFlavor - Full</strong>
                            <blockquote>
                                Planning on building a fully fledged out Management Portal with Dashboards and database driven logic and data combined with other cool features?
                                Then <strong>Full</strong> will ensure that you will have all the necessary examples to start building your next big project, including a well adopted architecture and trusted design patterns to guide your every step!
                            </blockquote>
                        </li>
                    </ul>
                    <p>
                        As with the previous version our aim here is to provide you with choice; whether you want it all, or just the bare minimum to get you started.
                        We want to make sure your way of working is supported and ensure that how you want to utilize the template is covered.
                        You can read more about the differences between each edition on the <a asp-controller="AspNetCore" asp-action="Editions">AspNetCore Editions</a> page.
                    </p>
                    <p>
                        Over time and with each update of @Settings.App 4.x we will be extending the amount of functionality that will get added to the <strong>@Settings.AppFlavor - Full</strong> version.
                        After we have established a stable community of users we will launch an initiative to invite you, our customers, to participate in determining which features you would like to see implemented as part of the next big @Settings.App update!
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-12">
        <div class="panel">
            <div class="panel-container show">
                <div class="panel-content">
                    <h2>Why @Settings.App for ASP.NET Core</h2>
                    <p>
                        ASP.NET Core is a developer friendly platform made up of tools, programming languages, and libraries for building many different types of applications.
                        It is a cross-platform, high-performance, open-source framework for building modern, cloud-based, Internet-connected applications.
                    </p>
                    <p>
                        This philosophy suits @Settings.App and matches our intent on how we want to present it to <strong>-you-</strong> our users.
                        Not everyone identifies themselves as a typical user and as such @Settings.App for @Settings.AppFlavor supports both ASP.NET Core MVC as well as ASP.NET Core RazorPages, using C# for server-side logic handling to provide model-binding and various other data-binding scenarios.
                        With <strong>.NET 5</strong> around the corner later this year we decided to use .NET Core 3.1 as the focus of this project.
                        But worry not, once <strong>.NET 5</strong> is fully released we'll be sure to provide you with a sleek update that covers all the newly introduced features to match the capabilities of @Settings.App for @Settings.AppFlavor!
                    </p>
                    <h3>Build secure apps</h3>
                    <p>
                        ASP.NET supports industry standard authentication protocols. Built-in features help protect your apps against cross-site scripting (XSS) and cross-site request forgery (CSRF). It is built on top of a lightweight, high-performance, and modular HTTP request pipeline that deploys and runs to Windows, Linux and MacOS!
                    </p>
                    <p>
                        ASP.NET provides a built-in user database with support for multi-factor authentication and external authentication with Google, Twitter, and more.
                    </p>
                    <h3>Identity Management</h3>
                    <p>
                        We have chosen to add support for ASP.NET Core Identity with this version of @Settings.App to not only give you an out of the box secure experience but also showcase how well we were able to have these two frameworks work together as they were shaped to match the @Settings.App 4.0 appearance.
                        All of this is resting comfortably on the back of ASP.NET EntityFramework Core which has been setup with Migration support to get you started!
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-12">
        <div class="alert alert-success">
            <h5 class="mb-0">@Settings.App for @Settings.AppFlavor is based on @Settings.App HTML <strong>v@(Settings.Theme.ThemeVersion)</strong>.</h5>
        </div>
    </div>
</div>